language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
branches:
  only:
    - master
    - dev
install: "pip install -r requirements.txt"
# command to run tests
script: 
  - cd rideshare
  - python manage.py test

