language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
branches:
  only:
    - master
    - dev
install: "pip install -r requirements.txt"
# command to run tests

defore_script:
  - psql -c'create database travis_postgis;' -U postgres
  - psql -c'CREATE EXTENSION postgis;' -U postgres -d travis_postgis
  - psql -f test_data.sql -U postgres -d travis_postgis

script: 
  - cd rideshare
  - python manage.py test

